name: admin-ui-moh
namespace: official
version: 1.1.0
author: Wazo Team
display_name: Music On Hold
min_wazo_version: 17.17
tags:
  - beta
  - application
homepage: https://github.com/wazo-pbx/wazo-admin-ui-moh
