name: admin-ui-moh
namespace: official
version: 1.1.1-4
author: Wazo Team
display_name: Music On Hold
min_wazo_version: 18.02
tags:
  - application
homepage: https://github.com/wazo-pbx/wazo-admin-ui-moh
icon: music
